title = "Harbor"
baseURL = "https://goharbor.io"
disableKinds = ["taxonomy", "taxonomyTerm"]
copyright = "The Harbor authors"

[params]
tagline = "Manage and serve container images in a secure environment"
description = "Our mission is to be the most secure, performant, scalable, and available cloud native repository for Kubernetes"
font_awesome_version = "5.12.0"

versions = ["1.10"]

[params.logos]
footer = "harbor-horizontal-white.png"
navbar = "harbor-horizontal-color.png"

[[params.fonts]]
name = "PT Sans"
sizes = [300, 400, 600, 700]
type = "sans_serif"

[[menu.main]]
name = "Community"
url = "/community"
weight = 1

[[menu.main]]
name = "Blog"
url = "/blog"
weight = 2

[outputs]
home = [ "HTML", "REDIRECTS" ]

[mediaTypes."text/netlify"]
delimiter = ""

[outputFormats.REDIRECTS]
mediaType = "text/netlify"
baseName = "_redirects"
